backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://pooshaz-onlinestore.netlify.app
display_url: https://pooshaz-onlinestore.netlify.app

collections:

  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Summer", "Winter", "Mid-Winter", "Eid"] }
      - { label: "Price (PKR)", name: "price", widget: "number" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
